    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        touch scripts/gcc-wrapper.py
        export GCC_WRAPPER=
        export LLVM_IAS=0
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
        export KBUILD_BUILD_HOST=Github-Action
        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
        if [ ! -z ${{ env.KSU_EXPECTED_SIZE }} ] && [ ! -z ${{ env.KSU_EXPECTED_HASH }} ]; then
          export KSU_EXPECTED_SIZE=${{ env.KSU_EXPECTED_SIZE }}
          export KSU_EXPECTED_HASH=${{ env.KSU_EXPECTED_HASH }}
        fi
        make -j$(nproc --all) LLVM_IAS=0 CC=clang LD=ld.lld O=out ARCH=${{ env.ARCH }} CROSS_COMPILE=aarch64-linux-gnu- ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} HOSTLDFLAGS="-Wl,--allow-multiple-definition" ${{ env.KERNEL_CONFIG }}
        if [[ "${{ env.ENABLE_CCACHE }}" == "true" ]]; then
            make -j$(nproc --all) LLVM_IAS=0 CC="ccache clang" LD=ld.lld O=out ARCH=${{ env.ARCH }} CROSS_COMPILE=aarch64-linux-gnu- ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} HOSTLDFLAGS="-Wl,--allow-multiple-definition"
        else
            make -j$(nproc --all) LLVM_IAS=0 CC=clang LD=ld.lld O=out ARCH=${{ env.ARCH }} CROSS_COMPILE=aarch64-linux-gnu- ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} HOSTLDFLAGS="-Wl,--allow-multiple-definition"
        fi
